apiVersion: v1
data:
  prometheus.yaml: |

    remote_write:
    - url: https://prometheus-prod-18-prod-ap-southeast-0.grafana.net/api/prom/push
      basic_auth:
        username: 707647
        password: glc_eyJvIjoiNzY3MzE5IiwibiI6InN0YWNrLTUwMzQzMS1obS10ZXN0IiwiayI6Ijk3THp0N3QyNjBqSEg1aTREOG82ZktXZSIsIm0iOnsiciI6InByb2QtYXAtc291dGhlYXN0LTAifX0=

    global:
      scrape_interval: 20s
      evaluation_interval: 20s
      scrape_timeout: 20s

    scrape_configs:
      - job_name: "kong"
        scrape_interval: 1m
        scrape_timeout: 1m
        static_configs:
          - targets: ["kong-kong-admin:8001"]

kind: ConfigMap
metadata:
  name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
  clusterIP: None
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"

      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
